# Generated by Django 5.2.7 on 2025-10-14 14:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Ruta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('distancia_total_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distancia Total (km)')),
                ('duracion_total_horas', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duración Total (horas)')),
                ('precio_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Promedio (USD)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'rutas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_tramo', models.IntegerField(default=1, help_text='Orden secuencial del tramo en la ruta', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden del Tramo')),
                ('medio_transporte', models.CharField(choices=[('bus', 'Bus'), ('avion', 'Avión'), ('barco', 'Barco'), ('auto', 'Auto')], max_length=20, verbose_name='Medio de Transporte')),
                ('distancia_tramo_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distancia del Tramo (km)')),
                ('duracion_tramo_horas', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duración del Tramo (horas)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del Tramo (USD)')),
                ('empresa_transporte', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa de Transporte')),
                ('horarios_disponibles', models.TextField(blank=True, help_text='Horarios de salida disponibles', null=True, verbose_name='Horarios Disponibles')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramos_destino', to='destinos.destino', verbose_name='Destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramos_origen', to='destinos.destino', verbose_name='Origen')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rutas.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Detalle de Ruta',
                'verbose_name_plural': 'Detalles de Ruta',
                'db_table': 'detalles_ruta',
                'ordering': ['ruta', 'orden_tramo'],
                'indexes': [models.Index(fields=['ruta', 'orden_tramo'], name='detalles_ru_ruta_id_d122f8_idx'), models.Index(fields=['medio_transporte'], name='detalles_ru_medio_t_f1bafa_idx')],
                'unique_together': {('ruta', 'orden_tramo')},
            },
        ),
    ]
