# Generated by Django 5.2.7 on 2025-10-14 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_personas', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Personas')),
                ('fecha_servicio', models.DateField(verbose_name='Fecha del Servicio')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Agregado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio', verbose_name='Servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'db_table': 'items_carrito',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'servicio', 'fecha_servicio')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('fecha_servicio', models.DateField(help_text='Fecha en que se prestará el servicio', verbose_name='Fecha del Servicio')),
                ('cantidad_personas', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Personas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del servicio al momento de la reserva', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario (USD)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal (USD)')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, help_text='12% IVA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Impuestos (USD)')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total (USD)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('codigo_reserva', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código de Reserva')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='servicios.servicio', verbose_name='Servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-fecha_reserva'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='reservas_usuario_2844a8_idx'), models.Index(fields=['fecha_servicio'], name='reservas_fecha_s_d84018_idx'), models.Index(fields=['estado'], name='reservas_estado_0b2aee_idx'), models.Index(fields=['codigo_reserva'], name='reservas_codigo__5a8d6b_idx')],
            },
        ),
    ]
