# Generated by Django 5.2.7 on 2025-10-14 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Clase de icono para representar la categoría', max_length=50, null=True, verbose_name='Icono CSS')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Destino')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('descripcion_corta', models.CharField(help_text='Resumen breve para listados', max_length=300, verbose_name='Descripción Corta')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('region', models.CharField(choices=[('costa', 'Costa'), ('sierra', 'Sierra'), ('oriente', 'Oriente/Amazonía'), ('galapagos', 'Galápagos')], max_length=20, verbose_name='Región')),
                ('latitud', models.DecimalField(decimal_places=7, help_text='Coordenada geográfica en formato decimal', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=7, help_text='Coordenada geográfica en formato decimal', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud')),
                ('clima', models.CharField(blank=True, help_text='Descripción del clima del destino', max_length=200, null=True, verbose_name='Clima')),
                ('altitud', models.IntegerField(blank=True, help_text='Altitud sobre el nivel del mar en metros', null=True, verbose_name='Altitud (msnm)')),
                ('mejor_epoca', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mejor Época para Visitar')),
                ('precio_promedio_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio mínimo por persona por día', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Promedio Mínimo (USD)')),
                ('precio_promedio_maximo', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio máximo por persona por día', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Promedio Máximo (USD)')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Promedio')),
                ('total_calificaciones', models.IntegerField(default=0, verbose_name='Total de Calificaciones')),
                ('visitas', models.IntegerField(default=0, verbose_name='Número de Visitas')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destino Destacado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='destinos.categoria', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destinos',
                'ordering': ['-destacado', '-calificacion_promedio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AtraccionTuristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Atracción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(help_text='Ej: Museo, Parque, Mirador, Playa, etc.', max_length=100, verbose_name='Tipo de Atracción')),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Entrada (USD)')),
                ('horario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Horario de Atención')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atracciones', to='destinos.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Atracción Turística',
                'verbose_name_plural': 'Atracciones Turísticas',
                'db_table': 'atracciones_turisticas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='destinos/%Y/%m/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título de la Imagen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='destinos.destino', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Imagen de Destino',
                'verbose_name_plural': 'Imágenes de Destinos',
                'db_table': 'imagenes_destino',
                'ordering': ['orden', '-es_principal'],
            },
        ),
        migrations.AddIndex(
            model_name='destino',
            index=models.Index(fields=['region'], name='destinos_region_c679d1_idx'),
        ),
        migrations.AddIndex(
            model_name='destino',
            index=models.Index(fields=['provincia'], name='destinos_provinc_1b26fd_idx'),
        ),
        migrations.AddIndex(
            model_name='destino',
            index=models.Index(fields=['calificacion_promedio'], name='destinos_calific_bd2b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='destino',
            index=models.Index(fields=['destacado'], name='destinos_destaca_21e15e_idx'),
        ),
    ]
