# Generated by Django 5.2.7 on 2025-10-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal del destino (opcional)', null=True, upload_to='destinos/', verbose_name='Imagen Principal'),
        ),
    ]
