# Generated by Django 5.2.7 on 2025-10-14 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('alojamiento', 'Alojamiento'), ('tour', 'Tour'), ('actividad', 'Actividad'), ('transporte', 'Transporte'), ('restaurante', 'Restaurante')], max_length=20, verbose_name='Tipo de Servicio')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio base del servicio', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio (USD)')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('capacidad_maxima', models.IntegerField(default=1, help_text='Número máximo de personas por reserva', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad Máxima')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio')),
                ('total_calificaciones', models.IntegerField(default=0, verbose_name='Total de Calificaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='destinos.categoria', verbose_name='Categoría')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='destinos.destino', verbose_name='Destino')),
                ('proveedor', models.ForeignKey(limit_choices_to={'rol__nombre': 'proveedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_proveedor', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['-calificacion_promedio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios/%Y/%m/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio',
                'verbose_name_plural': 'Imágenes de Servicios',
                'db_table': 'imagenes_servicio',
                'ordering': ['orden', '-es_principal'],
            },
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['tipo'], name='servicios_tipo_941af5_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['destino'], name='servicios_destino_8454e7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['disponible'], name='servicios_disponi_6c5638_idx'),
        ),
    ]
