# Generated by Django 5.2.7 on 2025-10-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_add_ubicacion_horarios'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicio',
            new_name='servicios_latitud_167b9a_idx',
            old_name='servicios_latitud_longitud_idx',
        ),
    ]
