# Generated by Django 5.2.7 on 2025-10-19 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicio_latitud_alter_servicio_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='latitud',
            field=models.DecimalField(decimal_places=8, help_text='Coordenada latitud (-90 a 90)', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='longitud',
            field=models.DecimalField(decimal_places=8, help_text='Coordenada longitud (-180 a 180)', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud'),
        ),
    ]
