# Generated by Django 5.2.7 on 2025-10-14 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar si el comentario es ofensivo', verbose_name='Activo')),
                ('moderado', models.BooleanField(default=False, help_text='Indica si el comentario fue revisado por moderación', verbose_name='Moderado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='servicios.servicio', verbose_name='Servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('calificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='calificaciones.calificacion', verbose_name='Calificación')),
                ('proveedor', models.ForeignKey(limit_choices_to={'rol__nombre': 'proveedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_calificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Respuesta a Calificación',
                'verbose_name_plural': 'Respuestas a Calificaciones',
                'db_table': 'respuestas_calificacion',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['servicio', 'activo'], name='calificacio_servici_a6e03a_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['puntuacion'], name='calificacio_puntuac_887b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('usuario', 'servicio')},
        ),
    ]
